apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
bases:
  - base
  - backend

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: nginx-ingress-controller
    path: backend/controller-patch.yaml
  - target:
      version: v1
      kind: ConfigMap
      name: nginx-configuration
    path: backend/controller-config-patch.yaml
