apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
bases:
  - base
  - backend

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: ingress-nginx-controller
    path: backend/controller-patch.yaml
