apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
commonLabels:
  app.kubernetes.io/name: ingress-nginx
  app.kubernetes.io/instance: ingress-nginx
  app.kubernetes.io/version: "0.43.0"
  app.kubernetes.io/component: controller
resources:
  - cluster-role-binding.yaml
  - cluster-role.yaml
  - deployment.yaml
  - ingress-class.yaml
  - role-binding.yaml
  - role.yaml
  - service.yaml
  - service-account.yaml
  - service-metrics.yaml
images:
  - name: k8s.gcr.io/ingress-nginx/controller
    newTag: v0.43.0@sha256:9bba603b99bf25f6d117cf1235b6598c16033ad027b143c90fa5b3cc583c5713
vars:
  - fieldref:
      fieldPath: metadata.name
    name: NGINX_CONFIGMAP_NAME
    objref:
      apiVersion: v1
      kind: ConfigMap
      name: ingress-nginx-controller
  - fieldref:
      fieldPath: metadata.name
    name: SERVICE_NAME
    objref:
      apiVersion: v1
      kind: Service
      name: ingress-nginx-controller
configMapGenerator:
  - name: ingress-nginx-controller
    literals:
      - body-size=64m
      - enable-vts-status="false"
      - hsts-include-subdomains="false"
      - proxy-body-size=10m
      - proxy-buffer-size=16k
      - proxy-connect-timeout="15"
      - proxy-read-timeout="600"
      - proxy-send-timeout="600"
      - server-name-hash-bucket-size="256"
generatorOptions:
  disableNameSuffixHash: true
